module.exports.config = {
    name: "deptrai",
    version: "0.0.1",
    hasPermssion: 0,
    credits: "SEN",
    description: "measure handsomeness",
    commandCategory: "other",
    cooldowns: 5
};

module.exports.run = function ({ api, event }) {
    const data = ["Your handsomeness is 1%","Your handsomeness is 2%","Your handsomeness is 3%","Your handsomeness is 4%","Your handsomeness is 5%","Your handsomeness is 6%","Your handsomeness is 7%","Your handsomeness is 8%","Your handsomeness is 9%"," your handsomeness is 10%","Your handsomeness is 11%","Your handsomeness is 12%","Your handsomeness is 13%","Your handsomeness is 14 %","Your handsomeness is 15%","Your handsomeness is 16%","Your handsomeness is 17%","Your handsomeness is 18%","Pretty your handsomeness is 19%","Your handsomeness is 20%","Your handsomeness is 21%","Your handsomeness is 22%","Your handsomeness is 23% ","Your handsomeness is 24%","Your handsomeness is 25%","Your handsomeness is 26%","Your handsomeness is 27%","Handsomeness your handsomeness is 28%","Your handsomeness is 29%","Your handsomeness is 30%","Your handsomeness is 31%","Your handsomeness is 32%" , "Your handsomeness is 33%","Your handsomeness is 34%","Your handsomeness is 35%","Your handsomeness is 36%","Your handsomeness is 37%","Your handsomeness is 38%","Your handsomeness is 39%"" your handsomeness is 40%","Your handsomeness is 41%","Your handsomeness is 42%","Your handsomeness is 43%","Your handsomeness is 44 %","Your handsomeness is 45%","Your handsomeness is 46%","Your handsomeness is 47%","Your handsomeness is 48%","Pretty your handsomeness is 49%","Your handsomeness is 50%","Your handsomeness is 51%","Your handsomeness is 52%","Your handsomeness is 53% ","Your handsomeness is 54%","Your handsomeness is 55%","Your handsomeness is 56%","Your handsomeness is 57%","Handsomeness your handsomeness is 58%","Your handsomeness is 59%","Your handsomeness is 60%","Your handsomeness is 61%","Your handsomeness is 62%" , "Your handsomeness is 63%","Your handsomeness is 64%","Your handsomeness is 65%","Your handsomeness is 66%","My handsomeness is you are 67%","Your handsomeness is 68%","Your handsomeness is 69%","Your handsomeness is your rai is 70%","Your handsomeness is 71%","Your handsomeness is 72%","Your handsomeness is 73%","Your handsomeness is 74% ","Your handsomeness is 75%","Your handsomeness is 76%","Your handsomeness is 77%","Your handsomeness is 78%","Handsomeness your handsomeness is 79%","Your handsomeness is 80%","Your handsomeness is 81%","Your handsomeness is 82%","Your handsomeness is 83%" , "Your handsomeness is 84%","Your handsomeness is 85%","Your handsomeness is 86%","Your handsomeness is 87%","My handsomeness is you are 88%","Your handsomeness is 89%","Your handsomeness is 90%","Your handsomeness is 91%","Your handsomeness is 92%", "Your handsomeness is 93%","Your handsomeness is 94%","Your handsomeness is 95%","Your handsomeness is 96%","Your handsomeness is 97%","Your handsomeness is 98%","Your handsomeness is 99%","Your handsomeness is 100%",
    ];
    return api.sendMessage(`${data[Math.floor(Math.random() * data.length)]}`, event.threadID, event.messageID);
}